// Context benchmarks are dated separately from the September 2026 fortunes.
// These are reported-dollar comparisons, without inflation adjustments.
window.WEALTH_CONTEXT = Object.freeze([
  {
    id: "income",
    fraction: 0.003,
    label: "A household’s income",
    title: "A whole year. A tiny square.",
    value: 83730,
    visual: "square",
    description:
      "Median US household income was $83,730 in 2024, before taxes. This is a year of income, compared with a stock of wealth.",
    source: "US Census Bureau · 2024 income, published 2025",
    url: "https://www.census.gov/newsroom/press-releases/2025/income-poverty-health-insurance-coverage.html",
    unit: "years of household income",
  },
  {
    id: "lifetime",
    fraction: 0.007,
    label: "A lifetime of earnings",
    title: "An entire working life.",
    value: 2800000,
    visual: "square",
    description:
      "Georgetown’s 2021 study estimated median lifetime earnings of $2.8 million for a bachelor’s degree holder working full-time, year-round. A high-school graduate’s estimate was $1.6 million. These are study-era estimates, not 2026 forecasts.",
    source: "Georgetown CEW · 2021 study, 2009–2019 data",
    url: "https://cew.georgetown.edu/cew-reports/collegepayoff2021/",
    unit: "working lifetimes at the $2.8M benchmark",
  },
  {
    id: "insurance",
    fraction: 0.025,
    label: "Family health insurance",
    title: "A year of family coverage.",
    value: 26993,
    visual: "square",
    description:
      "Average annual premiums for employer-sponsored family health insurance reached $26,993 in 2025. That includes employer and worker contributions; deductibles and other out-of-pocket costs are extra.",
    source: "KFF · 2025 Employer Health Benefits Survey",
    url: "https://www.kff.org/health-costs/2025-employer-health-benefits-survey/",
    unit: "family-years of premiums at this price",
  },
  {
    id: "amazon-pay",
    fraction: 0.045,
    label: "An Amazon worker’s pay",
    title: "A year on the warehouse floor.",
    value: 47840,
    visual: "square",
    description:
      "Amazon announced average US fulfillment and transportation pay above $23/hour in September 2025. At exactly $23 × 40 hours × 52 weeks, that is $47,840 before taxes. This illustration excludes overtime and benefits; actual earnings vary.",
    source: "Amazon · September 17, 2025 pay announcement",
    url: "https://www.aboutamazon.com/news/workplace/amazon-wage-increase-2025-fulfillment-transportation-employees",
    unit: "years of pay at the illustrated rate",
  },
  {
    id: "malaria",
    fraction: 0.08,
    label: "The malaria funding gap",
    title: "A small share. A global funding gap.",
    value: 5400000000,
    visual: "share",
    description:
      "WHO reported $3.9 billion invested in malaria in 2024 against a $9.3 billion target for 2025: a projected $5.4 billion gap. This is a funding comparison, not a price for permanently eradicating malaria.",
    source: "WHO · World Malaria Day 2026",
    url: "https://www.who.int/campaigns/world-malaria-day/2026",
  },
  {
    id: "food",
    fraction: 0.12,
    label: "Food assistance for 110 million",
    title: "110 million people. One year of assistance.",
    value: 13000000000,
    visual: "share",
    description:
      "The World Food Programme’s 2026 plan calls for $13 billion to reach 110 million vulnerable people. That is its annual operational requirement, not the cost of ending world hunger.",
    source: "UN World Food Programme · 2026 Global Outlook",
    url: "https://www.wfp.org/news/wfp-prioritize-feeding-110-million-hungriest-2026-global-hunger-deepens-amidst-uncertain",
  },
  {
    id: "cash",
    fraction: 0.16,
    label: "What 1% could mean",
    title: "What if 1% became $10,000 payments?",
    visual: "cash",
    description:
      "Imagine dividing just 1% of this fortune into one-time $10,000 payments to households. This is arithmetic, not an estimate of how many people would escape poverty. It ignores taxes, asset-sale effects, and delivery costs.",
    source: "Illustration calculated from the Forbes wealth snapshot",
    url: "https://www.forbes.com/real-time-billionaires/",
  },
  {
    id: "cancer",
    fraction: 0.38,
    label: "A year of US cancer care",
    title: "Cancer care, across an entire country.",
    value: 208900000000,
    visual: "share",
    description:
      "The National Cancer Institute estimates US cancer-care spending at $208.9 billion in 2020. This covers cancer-attributable medical services and oral prescriptions, not just chemotherapy. It is a historical annual benchmark in 2020 dollars, not a current price quote.",
    source: "National Cancer Institute · 2020 spending estimate",
    url: "https://progressreport.cancer.gov/after/economic_burden",
  },
  {
    id: "water",
    fraction: 0.62,
    label: "Safe water and sanitation",
    title: "Clean water is a question of scale, too.",
    value: 140800000000,
    low: 131400000000,
    visual: "share",
    description:
      "The World Bank estimates an annual water-supply and sanitation spending shortfall of $131.4–140.8 billion toward universal access. We use the upper end below. Infrastructure, institutions, and sustained funding are also needed.",
    source: "World Bank · Funding a Water-Secure Future (2024)",
    url: "https://www.worldbank.org/en/topic/water/publication/funding-a-water-secure-future",
  },
  {
    id: "four-hundred",
    fraction: 0.8,
    label: "The 400 richest Americans",
    title: "Now put 400 people in the picture.",
    value: 6600000000000,
    visual: "people",
    description:
      "The 2025 Forbes 400 held a combined $6.6 trillion. Each dot below is one person. This is a separate September 1, 2025 snapshot; the selected individual’s estimate is from September 2026, so this is a comparison across dates.",
    source: "Forbes 400 · 2025 annual list",
    url: "https://www.forbes.com/sites/forbes-spotlights/2025/09/09/forbes-unveils-2025-forbes-400-ranking-of-richest-americans/",
  },
  {
    id: "combined",
    fraction: 0.95,
    label: "And still a billionaire",
    title: "And still a billionaire.",
    value: 159200000000,
    visual: "share",
    description:
      "Add the $5.4B malaria gap, WFP’s $13B annual plan, and the $140.8B upper water-and-sanitation gap: $159.2 billion. This sums benchmarks with different dates and scopes, not a unified program budget or a promise of outcomes.",
    source: "Arithmetic from the WHO, WFP, and World Bank benchmarks above",
    references: ["malaria", "food", "water"],
  },
]);
